services:
  timescaledb:
    build:
      context: .
      dockerfile: Dockerfile.db
    restart: always
    platform: linux/amd64
    environment:
      POSTGRES_USER: bluesky
      POSTGRES_PASSWORD: bluesky_password
      POSTGRES_DB: bluesky_feed
    command: postgres -c max_locks_per_transaction=256 -c max_connections=100 -c shared_buffers=256MB
    ports:
      - "5432:5432"
    volumes:
      - bluesky-data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    # deploy:
    #   resources:
    #     limits:
    #       memory: 4g   # Increase this to allocate more memory
    #     reservations:
    #       memory: 1g # Ensures a minimum reserved memory
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  bluesky-data: