services:
  timescaledb:
    image: timescale/timescaledb:latest-pg17-bitnami
    platform: linux/amd64
    #env_file: ".env"
    environment:
      - POSTGRES_USER=bluesky
      - POSTGRES_PASSWORD=bluesky_password
      - POSTGRES_DB=bluesky_feed
    ports:
      - "5432:5432"
    volumes:
      - ./data/timescaledb:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB" ]
      interval: 10s
      timeout: 5s
      retries: 5
