services:
  timescaledb:
    image: timescale/timescaledb:latest-pg16
    restart: always
    platform: linux/amd64
    env_file: "timescale.env"
    ports:
      - "5432:5432"
    volumes:
      - bluesky-data:/var/lib/postgresql/data

    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  bluesky-data: